targets:
  $default:
    builders:
      isar_generator|isar_generator:
        options:
          # Web対応のため、JavaScriptで表現可能な整数範囲を使用
          # これにより、スキーマハッシュがJavaScript安全整数範囲内に収まる
          web_safe: true
