// Mocks generated by Mockito 5.4.4 from annotations
// in kokosid/test/core/services/act_dialogue_engine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:kokosid/core/models/user_context.dart' as _i2;
import 'package:kokosid/core/services/ai_service.dart' as _i4;
import 'package:kokosid/core/services/dialogue_history_service.dart' as _i3;
import 'package:kokosid/core/services/user_context_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserContext_0 extends _i1.SmartFake implements _i2.UserContext {
  _FakeUserContext_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDialogueEntry_1 extends _i1.SmartFake implements _i3.DialogueEntry {
  _FakeDialogueEntry_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePersonalizationContext_2 extends _i1.SmartFake
    implements _i3.PersonalizationContext {
  _FakePersonalizationContext_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIService extends _i1.Mock implements _i4.AIService {
  MockAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> complete(String? prompt) => (super.noSuchMethod(
        Invocation.method(
          #complete,
          [prompt],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #complete,
            [prompt],
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [UserContextService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserContextService extends _i1.Mock
    implements _i7.UserContextService {
  MockUserContextService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserContext> getUserContext(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserContext,
          [userUuid],
        ),
        returnValue: _i5.Future<_i2.UserContext>.value(_FakeUserContext_0(
          this,
          Invocation.method(
            #getUserContext,
            [userUuid],
          ),
        )),
      ) as _i5.Future<_i2.UserContext>);
}

/// A class which mocks [DialogueHistoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogueHistoryService extends _i1.Mock
    implements _i3.DialogueHistoryService {
  MockDialogueHistoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.DialogueEntry> saveDialogue({
    required String? uuid,
    required String? userUuid,
    required String? userInput,
    required String? aiResponse,
    required String? actProcess,
    String? emotionType,
    double? emotionConfidence,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDialogue,
          [],
          {
            #uuid: uuid,
            #userUuid: userUuid,
            #userInput: userInput,
            #aiResponse: aiResponse,
            #actProcess: actProcess,
            #emotionType: emotionType,
            #emotionConfidence: emotionConfidence,
          },
        ),
        returnValue: _i5.Future<_i3.DialogueEntry>.value(_FakeDialogueEntry_1(
          this,
          Invocation.method(
            #saveDialogue,
            [],
            {
              #uuid: uuid,
              #userUuid: userUuid,
              #userInput: userInput,
              #aiResponse: aiResponse,
              #actProcess: actProcess,
              #emotionType: emotionType,
              #emotionConfidence: emotionConfidence,
            },
          ),
        )),
      ) as _i5.Future<_i3.DialogueEntry>);

  @override
  _i5.Future<List<_i3.DialogueEntry>> getDialogueHistory(
    String? userUuid, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDialogueHistory,
          [userUuid],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<List<_i3.DialogueEntry>>.value(<_i3.DialogueEntry>[]),
      ) as _i5.Future<List<_i3.DialogueEntry>>);

  @override
  _i5.Future<List<_i3.DialogueEntry>> getRecentDialogues(
    String? userUuid, {
    int? days = 7,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentDialogues,
          [userUuid],
          {
            #days: days,
            #limit: limit,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.DialogueEntry>>.value(<_i3.DialogueEntry>[]),
      ) as _i5.Future<List<_i3.DialogueEntry>>);

  @override
  _i5.Future<List<_i3.DialogueEntry>> getDialoguesByEmotion(
    String? userUuid,
    String? emotionType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDialoguesByEmotion,
          [
            userUuid,
            emotionType,
          ],
        ),
        returnValue:
            _i5.Future<List<_i3.DialogueEntry>>.value(<_i3.DialogueEntry>[]),
      ) as _i5.Future<List<_i3.DialogueEntry>>);

  @override
  _i5.Future<_i3.PersonalizationContext> buildPersonalizationContext(
          String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildPersonalizationContext,
          [userUuid],
        ),
        returnValue: _i5.Future<_i3.PersonalizationContext>.value(
            _FakePersonalizationContext_2(
          this,
          Invocation.method(
            #buildPersonalizationContext,
            [userUuid],
          ),
        )),
      ) as _i5.Future<_i3.PersonalizationContext>);
}
