// Mocks generated by Mockito 5.4.4 from annotations
// in kokosid/test/core/services/data_deletion_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:isar/isar.dart' as _i7;
import 'package:kokosid/core/models/journal_entry.dart' as _i4;
import 'package:kokosid/core/models/self_esteem_score.dart' as _i5;
import 'package:kokosid/core/models/task.dart' as _i3;
import 'package:kokosid/core/models/user.dart' as _i2;
import 'package:kokosid/core/repositories/journal_repository.dart' as _i12;
import 'package:kokosid/core/repositories/self_esteem_repository.dart' as _i6;
import 'package:kokosid/core/repositories/task_repository.dart' as _i11;
import 'package:kokosid/core/repositories/user_repository.dart' as _i9;
import 'package:kokosid/core/services/database_service.dart' as _i8;
import 'package:kokosid/core/services/encrypted_storage_service.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTask_1 extends _i1.SmartFake implements _i3.Task {
  _FakeTask_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJournalEntry_2 extends _i1.SmartFake implements _i4.JournalEntry {
  _FakeJournalEntry_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelfEsteemScore_3 extends _i1.SmartFake
    implements _i5.SelfEsteemScore {
  _FakeSelfEsteemScore_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMonthlyScoreStats_4 extends _i1.SmartFake
    implements _i6.MonthlyScoreStats {
  _FakeMonthlyScoreStats_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIsar_5 extends _i1.SmartFake implements _i7.Isar {
  _FakeIsar_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseStats_6 extends _i1.SmartFake implements _i8.DatabaseStats {
  _FakeDatabaseStats_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i9.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.User> createUser(_i2.User? user) => (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [user],
        ),
        returnValue: _i10.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #createUser,
            [user],
          ),
        )),
      ) as _i10.Future<_i2.User>);

  @override
  _i10.Future<_i2.User?> getUserByUuid(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #getUserByUuid,
          [uuid],
        ),
        returnValue: _i10.Future<_i2.User?>.value(),
      ) as _i10.Future<_i2.User?>);

  @override
  _i10.Future<List<_i2.User>> getAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
        ),
        returnValue: _i10.Future<List<_i2.User>>.value(<_i2.User>[]),
      ) as _i10.Future<List<_i2.User>>);

  @override
  _i10.Future<_i2.User> updateUser(_i2.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i10.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #updateUser,
            [user],
          ),
        )),
      ) as _i10.Future<_i2.User>);

  @override
  _i10.Future<bool> deleteUser(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [uuid],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i2.User?> getFirstUser() => (super.noSuchMethod(
        Invocation.method(
          #getFirstUser,
          [],
        ),
        returnValue: _i10.Future<_i2.User?>.value(),
      ) as _i10.Future<_i2.User?>);

  @override
  _i10.Future<void> updateLastActive(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #updateLastActive,
          [uuid],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> completeOnboarding(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #completeOnboarding,
          [uuid],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i11.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i3.Task> createTask(_i3.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
        ),
        returnValue: _i10.Future<_i3.Task>.value(_FakeTask_1(
          this,
          Invocation.method(
            #createTask,
            [task],
          ),
        )),
      ) as _i10.Future<_i3.Task>);

  @override
  _i10.Future<_i3.Task?> getTaskByUuid(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #getTaskByUuid,
          [uuid],
        ),
        returnValue: _i10.Future<_i3.Task?>.value(),
      ) as _i10.Future<_i3.Task?>);

  @override
  _i10.Future<List<_i3.Task>> getTasksByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByUser,
          [userUuid],
        ),
        returnValue: _i10.Future<List<_i3.Task>>.value(<_i3.Task>[]),
      ) as _i10.Future<List<_i3.Task>>);

  @override
  _i10.Future<List<_i3.Task>> getPendingTasksByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingTasksByUser,
          [userUuid],
        ),
        returnValue: _i10.Future<List<_i3.Task>>.value(<_i3.Task>[]),
      ) as _i10.Future<List<_i3.Task>>);

  @override
  _i10.Future<List<_i3.Task>> getCompletedTasksByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedTasksByUser,
          [userUuid],
        ),
        returnValue: _i10.Future<List<_i3.Task>>.value(<_i3.Task>[]),
      ) as _i10.Future<List<_i3.Task>>);

  @override
  _i10.Future<List<_i3.Task>> getTodayTasks(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodayTasks,
          [userUuid],
        ),
        returnValue: _i10.Future<List<_i3.Task>>.value(<_i3.Task>[]),
      ) as _i10.Future<List<_i3.Task>>);

  @override
  _i10.Future<List<_i3.Task>> getMicroTasks(String? originalTaskUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMicroTasks,
          [originalTaskUuid],
        ),
        returnValue: _i10.Future<List<_i3.Task>>.value(<_i3.Task>[]),
      ) as _i10.Future<List<_i3.Task>>);

  @override
  _i10.Future<_i3.Task> updateTask(_i3.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i10.Future<_i3.Task>.value(_FakeTask_1(
          this,
          Invocation.method(
            #updateTask,
            [task],
          ),
        )),
      ) as _i10.Future<_i3.Task>);

  @override
  _i10.Future<_i3.Task> completeTask(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #completeTask,
          [uuid],
        ),
        returnValue: _i10.Future<_i3.Task>.value(_FakeTask_1(
          this,
          Invocation.method(
            #completeTask,
            [uuid],
          ),
        )),
      ) as _i10.Future<_i3.Task>);

  @override
  _i10.Future<_i3.Task> startTask(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #startTask,
          [uuid],
        ),
        returnValue: _i10.Future<_i3.Task>.value(_FakeTask_1(
          this,
          Invocation.method(
            #startTask,
            [uuid],
          ),
        )),
      ) as _i10.Future<_i3.Task>);

  @override
  _i10.Future<bool> deleteTask(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [uuid],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<int> getCompletedTaskCount(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedTaskCount,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<int> getTotalTaskCount(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalTaskCount,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<List<_i3.Task>> getTasksByDateRange(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByDateRange,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i10.Future<List<_i3.Task>>.value(<_i3.Task>[]),
      ) as _i10.Future<List<_i3.Task>>);
}

/// A class which mocks [JournalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalRepository extends _i1.Mock implements _i12.JournalRepository {
  MockJournalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i4.JournalEntry> createEntry(_i4.JournalEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEntry,
          [entry],
        ),
        returnValue: _i10.Future<_i4.JournalEntry>.value(_FakeJournalEntry_2(
          this,
          Invocation.method(
            #createEntry,
            [entry],
          ),
        )),
      ) as _i10.Future<_i4.JournalEntry>);

  @override
  _i10.Future<_i4.JournalEntry> createEncryptedEntry({
    required String? uuid,
    required String? userUuid,
    required String? content,
    String? audioUrl,
    _i4.EmotionType? emotion,
    double? emotionConfidence,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEncryptedEntry,
          [],
          {
            #uuid: uuid,
            #userUuid: userUuid,
            #content: content,
            #audioUrl: audioUrl,
            #emotion: emotion,
            #emotionConfidence: emotionConfidence,
          },
        ),
        returnValue: _i10.Future<_i4.JournalEntry>.value(_FakeJournalEntry_2(
          this,
          Invocation.method(
            #createEncryptedEntry,
            [],
            {
              #uuid: uuid,
              #userUuid: userUuid,
              #content: content,
              #audioUrl: audioUrl,
              #emotion: emotion,
              #emotionConfidence: emotionConfidence,
            },
          ),
        )),
      ) as _i10.Future<_i4.JournalEntry>);

  @override
  _i10.Future<_i4.JournalEntry?> getEntryByUuid(String? uuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntryByUuid,
          [uuid],
        ),
        returnValue: _i10.Future<_i4.JournalEntry?>.value(),
      ) as _i10.Future<_i4.JournalEntry?>);

  @override
  _i10.Future<List<_i4.JournalEntry>> getEntriesByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByUser,
          [userUuid],
        ),
        returnValue:
            _i10.Future<List<_i4.JournalEntry>>.value(<_i4.JournalEntry>[]),
      ) as _i10.Future<List<_i4.JournalEntry>>);

  @override
  _i10.Future<List<_i4.JournalEntry>> getTodayEntries(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodayEntries,
          [userUuid],
        ),
        returnValue:
            _i10.Future<List<_i4.JournalEntry>>.value(<_i4.JournalEntry>[]),
      ) as _i10.Future<List<_i4.JournalEntry>>);

  @override
  _i10.Future<List<_i4.JournalEntry>> getEntriesByDateRange(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByDateRange,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue:
            _i10.Future<List<_i4.JournalEntry>>.value(<_i4.JournalEntry>[]),
      ) as _i10.Future<List<_i4.JournalEntry>>);

  @override
  _i10.Future<List<_i4.JournalEntry>> getEntriesByEmotion(
    String? userUuid,
    _i4.EmotionType? emotion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByEmotion,
          [
            userUuid,
            emotion,
          ],
        ),
        returnValue:
            _i10.Future<List<_i4.JournalEntry>>.value(<_i4.JournalEntry>[]),
      ) as _i10.Future<List<_i4.JournalEntry>>);

  @override
  _i10.Future<_i4.JournalEntry> updateEntry(_i4.JournalEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [entry],
        ),
        returnValue: _i10.Future<_i4.JournalEntry>.value(_FakeJournalEntry_2(
          this,
          Invocation.method(
            #updateEntry,
            [entry],
          ),
        )),
      ) as _i10.Future<_i4.JournalEntry>);

  @override
  _i10.Future<bool> deleteEntry(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [uuid],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  String? decryptContent(_i4.JournalEntry? entry) =>
      (super.noSuchMethod(Invocation.method(
        #decryptContent,
        [entry],
      )) as String?);

  @override
  String? decryptAiResponse(_i4.JournalEntry? entry) =>
      (super.noSuchMethod(Invocation.method(
        #decryptAiResponse,
        [entry],
      )) as String?);

  @override
  _i10.Future<Map<_i4.EmotionType, int>> getEmotionStatistics(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEmotionStatistics,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i10.Future<Map<_i4.EmotionType, int>>.value(
            <_i4.EmotionType, int>{}),
      ) as _i10.Future<Map<_i4.EmotionType, int>>);

  @override
  _i10.Future<List<_i4.JournalEntry>> getUnsyncedEntries(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedEntries,
          [userUuid],
        ),
        returnValue:
            _i10.Future<List<_i4.JournalEntry>>.value(<_i4.JournalEntry>[]),
      ) as _i10.Future<List<_i4.JournalEntry>>);

  @override
  _i10.Future<void> markAsSynced(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [uuid],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [SelfEsteemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSelfEsteemRepository extends _i1.Mock
    implements _i6.SelfEsteemRepository {
  MockSelfEsteemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i5.SelfEsteemScore> createScore(_i5.SelfEsteemScore? score) =>
      (super.noSuchMethod(
        Invocation.method(
          #createScore,
          [score],
        ),
        returnValue:
            _i10.Future<_i5.SelfEsteemScore>.value(_FakeSelfEsteemScore_3(
          this,
          Invocation.method(
            #createScore,
            [score],
          ),
        )),
      ) as _i10.Future<_i5.SelfEsteemScore>);

  @override
  _i10.Future<_i5.SelfEsteemScore?> getScoreByUuid(String? uuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoreByUuid,
          [uuid],
        ),
        returnValue: _i10.Future<_i5.SelfEsteemScore?>.value(),
      ) as _i10.Future<_i5.SelfEsteemScore?>);

  @override
  _i10.Future<List<_i5.SelfEsteemScore>> getScoresByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoresByUser,
          [userUuid],
        ),
        returnValue: _i10.Future<List<_i5.SelfEsteemScore>>.value(
            <_i5.SelfEsteemScore>[]),
      ) as _i10.Future<List<_i5.SelfEsteemScore>>);

  @override
  _i10.Future<_i5.SelfEsteemScore?> getLatestScore(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestScore,
          [userUuid],
        ),
        returnValue: _i10.Future<_i5.SelfEsteemScore?>.value(),
      ) as _i10.Future<_i5.SelfEsteemScore?>);

  @override
  _i10.Future<_i5.SelfEsteemScore?> getTodayScore(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodayScore,
          [userUuid],
        ),
        returnValue: _i10.Future<_i5.SelfEsteemScore?>.value(),
      ) as _i10.Future<_i5.SelfEsteemScore?>);

  @override
  _i10.Future<List<_i5.SelfEsteemScore>> getScoresByDateRange(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoresByDateRange,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i10.Future<List<_i5.SelfEsteemScore>>.value(
            <_i5.SelfEsteemScore>[]),
      ) as _i10.Future<List<_i5.SelfEsteemScore>>);

  @override
  _i10.Future<List<_i5.SelfEsteemScore>> getRecentScores(
    String? userUuid,
    int? days,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentScores,
          [
            userUuid,
            days,
          ],
        ),
        returnValue: _i10.Future<List<_i5.SelfEsteemScore>>.value(
            <_i5.SelfEsteemScore>[]),
      ) as _i10.Future<List<_i5.SelfEsteemScore>>);

  @override
  _i10.Future<_i5.SelfEsteemScore> updateScore(_i5.SelfEsteemScore? score) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateScore,
          [score],
        ),
        returnValue:
            _i10.Future<_i5.SelfEsteemScore>.value(_FakeSelfEsteemScore_3(
          this,
          Invocation.method(
            #updateScore,
            [score],
          ),
        )),
      ) as _i10.Future<_i5.SelfEsteemScore>);

  @override
  _i10.Future<bool> deleteScore(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #deleteScore,
          [uuid],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<double?> getAverageScore(
    String? userUuid,
    int? days,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAverageScore,
          [
            userUuid,
            days,
          ],
        ),
        returnValue: _i10.Future<double?>.value(),
      ) as _i10.Future<double?>);

  @override
  _i10.Future<_i6.ScoreTrend> getScoreTrend(
    String? userUuid,
    int? days,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoreTrend,
          [
            userUuid,
            days,
          ],
        ),
        returnValue:
            _i10.Future<_i6.ScoreTrend>.value(_i6.ScoreTrend.improving),
      ) as _i10.Future<_i6.ScoreTrend>);

  @override
  _i10.Future<_i6.MonthlyScoreStats> getMonthlyStats(
    String? userUuid,
    DateTime? month,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthlyStats,
          [
            userUuid,
            month,
          ],
        ),
        returnValue:
            _i10.Future<_i6.MonthlyScoreStats>.value(_FakeMonthlyScoreStats_4(
          this,
          Invocation.method(
            #getMonthlyStats,
            [
              userUuid,
              month,
            ],
          ),
        )),
      ) as _i10.Future<_i6.MonthlyScoreStats>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i8.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Isar get isar => (super.noSuchMethod(
        Invocation.getter(#isar),
        returnValue: _FakeIsar_5(
          this,
          Invocation.getter(#isar),
        ),
      ) as _i7.Isar);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> getDatabaseSize() => (super.noSuchMethod(
        Invocation.method(
          #getDatabaseSize,
          [],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<void> clearUserData(String? userUuid) => (super.noSuchMethod(
        Invocation.method(
          #clearUserData,
          [userUuid],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i8.DatabaseStats> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue: _i10.Future<_i8.DatabaseStats>.value(_FakeDatabaseStats_6(
          this,
          Invocation.method(
            #getStats,
            [],
          ),
        )),
      ) as _i10.Future<_i8.DatabaseStats>);

  @override
  _i10.Future<bool> performHealthCheck() => (super.noSuchMethod(
        Invocation.method(
          #performHealthCheck,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> optimize() => (super.noSuchMethod(
        Invocation.method(
          #optimize,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [EncryptedStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptedStorageService extends _i1.Mock
    implements _i13.EncryptedStorageService {
  MockEncryptedStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i4.JournalEntry> saveEncryptedJournalEntry({
    required String? uuid,
    required String? userUuid,
    required String? content,
    String? audioUrl,
    String? transcription,
    _i4.EmotionType? emotion,
    double? emotionConfidence,
    String? aiResponse,
    String? aiReflection,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEncryptedJournalEntry,
          [],
          {
            #uuid: uuid,
            #userUuid: userUuid,
            #content: content,
            #audioUrl: audioUrl,
            #transcription: transcription,
            #emotion: emotion,
            #emotionConfidence: emotionConfidence,
            #aiResponse: aiResponse,
            #aiReflection: aiReflection,
          },
        ),
        returnValue: _i10.Future<_i4.JournalEntry>.value(_FakeJournalEntry_2(
          this,
          Invocation.method(
            #saveEncryptedJournalEntry,
            [],
            {
              #uuid: uuid,
              #userUuid: userUuid,
              #content: content,
              #audioUrl: audioUrl,
              #transcription: transcription,
              #emotion: emotion,
              #emotionConfidence: emotionConfidence,
              #aiResponse: aiResponse,
              #aiReflection: aiReflection,
            },
          ),
        )),
      ) as _i10.Future<_i4.JournalEntry>);

  @override
  String? decryptJournalContent(_i4.JournalEntry? entry) =>
      (super.noSuchMethod(Invocation.method(
        #decryptJournalContent,
        [entry],
      )) as String?);

  @override
  String? decryptJournalAiResponse(_i4.JournalEntry? entry) =>
      (super.noSuchMethod(Invocation.method(
        #decryptJournalAiResponse,
        [entry],
      )) as String?);

  @override
  _i10.Future<void> saveEncryptedUserSettings(
    String? userUuid,
    Map<String, dynamic>? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEncryptedUserSettings,
          [
            userUuid,
            settings,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<Map<String, dynamic>?> loadEncryptedUserSettings(
          String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadEncryptedUserSettings,
          [userUuid],
        ),
        returnValue: _i10.Future<Map<String, dynamic>?>.value(),
      ) as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<String> createEncryptedBackup(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEncryptedBackup,
          [userUuid],
        ),
        returnValue: _i10.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #createEncryptedBackup,
            [userUuid],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> restoreFromEncryptedBackup(String? encryptedBackup) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreFromEncryptedBackup,
          [encryptedBackup],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> verifyDataIntegrity(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyDataIntegrity,
          [userUuid],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> reencryptAllData(
    String? userUuid,
    String? oldKey,
    String? newKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reencryptAllData,
          [
            userUuid,
            oldKey,
            newKey,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}
