// Mocks generated by Mockito 5.4.4 from annotations
// in kokosid/test/core/services/offline_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:kokosid/core/models/journal_entry.dart' as _i9;
import 'package:kokosid/core/models/self_esteem_score.dart' as _i10;
import 'package:kokosid/core/models/task.dart' as _i8;
import 'package:kokosid/core/models/user.dart' as _i7;
import 'package:kokosid/core/services/database_service.dart' as _i3;
import 'package:kokosid/core/services/local_storage_service.dart' as _i2;
import 'package:kokosid/core/services/network_service.dart' as _i6;
import 'package:kokosid/core/services/sync_queue_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocalStorageService_0 extends _i1.SmartFake
    implements _i2.LocalStorageService {
  _FakeLocalStorageService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseStats_1 extends _i1.SmartFake implements _i3.DatabaseStats {
  _FakeDatabaseStats_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncResult_2 extends _i1.SmartFake implements _i4.SyncResult {
  _FakeSyncResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalStorageService get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeLocalStorageService_0(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i2.LocalStorageService);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getDatabaseSize() => (super.noSuchMethod(
        Invocation.method(
          #getDatabaseSize,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> clearUserData(String? userUuid) => (super.noSuchMethod(
        Invocation.method(
          #clearUserData,
          [userUuid],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.DatabaseStats> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue: _i5.Future<_i3.DatabaseStats>.value(_FakeDatabaseStats_1(
          this,
          Invocation.method(
            #getStats,
            [],
          ),
        )),
      ) as _i5.Future<_i3.DatabaseStats>);

  @override
  _i5.Future<bool> performHealthCheck() => (super.noSuchMethod(
        Invocation.method(
          #performHealthCheck,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> optimize() => (super.noSuchMethod(
        Invocation.method(
          #optimize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [NetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkService extends _i1.Mock implements _i6.NetworkService {
  MockNetworkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<bool> get onlineStream => (super.noSuchMethod(
        Invocation.getter(#onlineStream),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
      ) as bool);

  @override
  bool get isOffline => (super.noSuchMethod(
        Invocation.getter(#isOffline),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SyncQueueService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncQueueService extends _i1.Mock implements _i4.SyncQueueService {
  MockSyncQueueService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get queueSize => (super.noSuchMethod(
        Invocation.getter(#queueSize),
        returnValue: 0,
      ) as int);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  bool get isSyncing => (super.noSuchMethod(
        Invocation.getter(#isSyncing),
        returnValue: false,
      ) as bool);

  @override
  void enqueueUserSync(_i7.User? user) => super.noSuchMethod(
        Invocation.method(
          #enqueueUserSync,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void enqueueTaskSync(_i8.Task? task) => super.noSuchMethod(
        Invocation.method(
          #enqueueTaskSync,
          [task],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void enqueueJournalEntrySync(_i9.JournalEntry? entry) => super.noSuchMethod(
        Invocation.method(
          #enqueueJournalEntrySync,
          [entry],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void enqueueSelfEsteemScoreSync(_i10.SelfEsteemScore? score) =>
      super.noSuchMethod(
        Invocation.method(
          #enqueueSelfEsteemScoreSync,
          [score],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i4.SyncResult> sync() => (super.noSuchMethod(
        Invocation.method(
          #sync,
          [],
        ),
        returnValue: _i5.Future<_i4.SyncResult>.value(_FakeSyncResult_2(
          this,
          Invocation.method(
            #sync,
            [],
          ),
        )),
      ) as _i5.Future<_i4.SyncResult>);

  @override
  void startAutoSync({Duration? interval = const Duration(minutes: 5)}) =>
      super.noSuchMethod(
        Invocation.method(
          #startAutoSync,
          [],
          {#interval: interval},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopAutoSync() => super.noSuchMethod(
        Invocation.method(
          #stopAutoSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearQueue() => super.noSuchMethod(
        Invocation.method(
          #clearQueue,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i4.SyncOperation> getQueueContents() => (super.noSuchMethod(
        Invocation.method(
          #getQueueContents,
          [],
        ),
        returnValue: <_i4.SyncOperation>[],
      ) as List<_i4.SyncOperation>);

  @override
  int getOperationCount(_i4.SyncOperationType? type) => (super.noSuchMethod(
        Invocation.method(
          #getOperationCount,
          [type],
        ),
        returnValue: 0,
      ) as int);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
