// Mocks generated by Mockito 5.4.4 from annotations
// in kokosid/test/core/services/payment_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kokosid/core/services/payment_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaymentResult_0 extends _i1.SmartFake implements _i2.PaymentResult {
  _FakePaymentResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i2.PaymentService {
  MockPaymentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.PaymentResult> purchaseProPlan(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #purchaseProPlan,
          [userId],
        ),
        returnValue: _i3.Future<_i2.PaymentResult>.value(_FakePaymentResult_0(
          this,
          Invocation.method(
            #purchaseProPlan,
            [userId],
          ),
        )),
      ) as _i3.Future<_i2.PaymentResult>);

  @override
  _i3.Future<_i2.PaymentResult> purchaseGems(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #purchaseGems,
          [userId],
        ),
        returnValue: _i3.Future<_i2.PaymentResult>.value(_FakePaymentResult_0(
          this,
          Invocation.method(
            #purchaseGems,
            [userId],
          ),
        )),
      ) as _i3.Future<_i2.PaymentResult>);

  @override
  _i3.Future<bool> verifyReceipt(String? receipt) => (super.noSuchMethod(
        Invocation.method(
          #verifyReceipt,
          [receipt],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> processRefund(String? transactionId) => (super.noSuchMethod(
        Invocation.method(
          #processRefund,
          [transactionId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i2.Purchase>> restorePurchases() => (super.noSuchMethod(
        Invocation.method(
          #restorePurchases,
          [],
        ),
        returnValue: _i3.Future<List<_i2.Purchase>>.value(<_i2.Purchase>[]),
      ) as _i3.Future<List<_i2.Purchase>>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
