// Mocks generated by Mockito 5.4.4 from annotations
// in kokosid/test/core/services/personalized_praise_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:kokosid/core/models/success_experience.dart' as _i3;
import 'package:kokosid/core/models/user_context.dart' as _i2;
import 'package:kokosid/core/repositories/success_experience_repository.dart'
    as _i8;
import 'package:kokosid/core/services/ai_service.dart' as _i4;
import 'package:kokosid/core/services/user_context_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserContext_0 extends _i1.SmartFake implements _i2.UserContext {
  _FakeUserContext_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSuccessExperience_1 extends _i1.SmartFake
    implements _i3.SuccessExperience {
  _FakeSuccessExperience_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIService extends _i1.Mock implements _i4.AIService {
  MockAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> complete(String? prompt) => (super.noSuchMethod(
        Invocation.method(
          #complete,
          [prompt],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #complete,
            [prompt],
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [UserContextService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserContextService extends _i1.Mock
    implements _i7.UserContextService {
  MockUserContextService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserContext> getUserContext(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserContext,
          [userUuid],
        ),
        returnValue: _i5.Future<_i2.UserContext>.value(_FakeUserContext_0(
          this,
          Invocation.method(
            #getUserContext,
            [userUuid],
          ),
        )),
      ) as _i5.Future<_i2.UserContext>);
}

/// A class which mocks [SuccessExperienceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuccessExperienceRepository extends _i1.Mock
    implements _i8.SuccessExperienceRepository {
  MockSuccessExperienceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.SuccessExperience> createSuccessExperience(
          _i3.SuccessExperience? experience) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSuccessExperience,
          [experience],
        ),
        returnValue:
            _i5.Future<_i3.SuccessExperience>.value(_FakeSuccessExperience_1(
          this,
          Invocation.method(
            #createSuccessExperience,
            [experience],
          ),
        )),
      ) as _i5.Future<_i3.SuccessExperience>);

  @override
  _i5.Future<_i3.SuccessExperience?> getSuccessExperience(String? uuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSuccessExperience,
          [uuid],
        ),
        returnValue: _i5.Future<_i3.SuccessExperience?>.value(),
      ) as _i5.Future<_i3.SuccessExperience?>);

  @override
  _i5.Future<List<_i3.SuccessExperience>> getUserSuccessExperiences(
          String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserSuccessExperiences,
          [userUuid],
        ),
        returnValue: _i5.Future<List<_i3.SuccessExperience>>.value(
            <_i3.SuccessExperience>[]),
      ) as _i5.Future<List<_i3.SuccessExperience>>);

  @override
  _i5.Future<List<_i3.SuccessExperience>> searchByTag(
    String? userUuid,
    String? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByTag,
          [
            userUuid,
            tag,
          ],
        ),
        returnValue: _i5.Future<List<_i3.SuccessExperience>>.value(
            <_i3.SuccessExperience>[]),
      ) as _i5.Future<List<_i3.SuccessExperience>>);

  @override
  _i5.Future<List<_i3.SuccessExperience>> searchByEmotion(
    String? userUuid,
    String? emotion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByEmotion,
          [
            userUuid,
            emotion,
          ],
        ),
        returnValue: _i5.Future<List<_i3.SuccessExperience>>.value(
            <_i3.SuccessExperience>[]),
      ) as _i5.Future<List<_i3.SuccessExperience>>);

  @override
  _i5.Future<List<_i3.SuccessExperience>> getRecentSuccessExperiences(
    String? userUuid, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentSuccessExperiences,
          [userUuid],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i3.SuccessExperience>>.value(
            <_i3.SuccessExperience>[]),
      ) as _i5.Future<List<_i3.SuccessExperience>>);

  @override
  _i5.Future<List<_i3.SuccessExperience>> getMostReferencedSuccessExperiences(
    String? userUuid, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMostReferencedSuccessExperiences,
          [userUuid],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i3.SuccessExperience>>.value(
            <_i3.SuccessExperience>[]),
      ) as _i5.Future<List<_i3.SuccessExperience>>);

  @override
  _i5.Future<void> updateSuccessExperience(_i3.SuccessExperience? experience) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSuccessExperience,
          [experience],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteSuccessExperience(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #deleteSuccessExperience,
          [uuid],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> recordReference(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #recordReference,
          [uuid],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
