// Mocks generated by Mockito 5.4.4 from annotations
// in kokosid/test/core/services/precision_nudging_system_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i9;
import 'package:kokosid/core/models/journal_entry.dart' as _i3;
import 'package:kokosid/core/models/notification_tone.dart' as _i8;
import 'package:kokosid/core/models/task.dart' as _i6;
import 'package:kokosid/core/models/user_context.dart' as _i2;
import 'package:kokosid/core/repositories/journal_repository.dart' as _i11;
import 'package:kokosid/core/services/notification_service.dart' as _i7;
import 'package:kokosid/core/services/productive_hour_predictor.dart' as _i4;
import 'package:kokosid/core/services/user_context_service.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserContext_1 extends _i1.SmartFake implements _i2.UserContext {
  _FakeUserContext_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJournalEntry_2 extends _i1.SmartFake implements _i3.JournalEntry {
  _FakeJournalEntry_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductiveHourPredictor].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductiveHourPredictor extends _i1.Mock
    implements _i4.ProductiveHourPredictor {
  MockProductiveHourPredictor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<int> predictOptimalTime(
    String? userUuid,
    _i6.Task? task,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #predictOptimalTime,
          [
            userUuid,
            task,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<Map<int, double>> getHourlyCompletionRates(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHourlyCompletionRates,
          [userUuid],
        ),
        returnValue: _i5.Future<Map<int, double>>.value(<int, double>{}),
      ) as _i5.Future<Map<int, double>>);

  @override
  DateTime getNextOccurrence(int? hour) => (super.noSuchMethod(
        Invocation.method(
          #getNextOccurrence,
          [hour],
        ),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.method(
            #getNextOccurrence,
            [hour],
          ),
        ),
      ) as DateTime);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i7.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> schedule({
    required _i8.NotificationMessage? message,
    required DateTime? scheduledTime,
    required _i8.RetryStrategy? retryStrategy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #schedule,
          [],
          {
            #message: message,
            #scheduledTime: scheduledTime,
            #retryStrategy: retryStrategy,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sendImmediate(_i8.NotificationMessage? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendImmediate,
          [message],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancel(String? taskUuid) => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [taskUuid],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.PendingNotificationRequest>> getPendingNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingNotifications,
          [],
        ),
        returnValue: _i5.Future<List<_i9.PendingNotificationRequest>>.value(
            <_i9.PendingNotificationRequest>[]),
      ) as _i5.Future<List<_i9.PendingNotificationRequest>>);
}

/// A class which mocks [UserContextService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserContextService extends _i1.Mock
    implements _i10.UserContextService {
  MockUserContextService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserContext> getUserContext(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserContext,
          [userUuid],
        ),
        returnValue: _i5.Future<_i2.UserContext>.value(_FakeUserContext_1(
          this,
          Invocation.method(
            #getUserContext,
            [userUuid],
          ),
        )),
      ) as _i5.Future<_i2.UserContext>);
}

/// A class which mocks [JournalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalRepository extends _i1.Mock implements _i11.JournalRepository {
  MockJournalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.JournalEntry> createEntry(_i3.JournalEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEntry,
          [entry],
        ),
        returnValue: _i5.Future<_i3.JournalEntry>.value(_FakeJournalEntry_2(
          this,
          Invocation.method(
            #createEntry,
            [entry],
          ),
        )),
      ) as _i5.Future<_i3.JournalEntry>);

  @override
  _i5.Future<_i3.JournalEntry> createEncryptedEntry({
    required String? uuid,
    required String? userUuid,
    required String? content,
    String? audioUrl,
    _i3.EmotionType? emotion,
    double? emotionConfidence,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEncryptedEntry,
          [],
          {
            #uuid: uuid,
            #userUuid: userUuid,
            #content: content,
            #audioUrl: audioUrl,
            #emotion: emotion,
            #emotionConfidence: emotionConfidence,
          },
        ),
        returnValue: _i5.Future<_i3.JournalEntry>.value(_FakeJournalEntry_2(
          this,
          Invocation.method(
            #createEncryptedEntry,
            [],
            {
              #uuid: uuid,
              #userUuid: userUuid,
              #content: content,
              #audioUrl: audioUrl,
              #emotion: emotion,
              #emotionConfidence: emotionConfidence,
            },
          ),
        )),
      ) as _i5.Future<_i3.JournalEntry>);

  @override
  _i5.Future<_i3.JournalEntry?> getEntryByUuid(String? uuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntryByUuid,
          [uuid],
        ),
        returnValue: _i5.Future<_i3.JournalEntry?>.value(),
      ) as _i5.Future<_i3.JournalEntry?>);

  @override
  _i5.Future<List<_i3.JournalEntry>> getEntriesByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByUser,
          [userUuid],
        ),
        returnValue:
            _i5.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i5.Future<List<_i3.JournalEntry>>);

  @override
  _i5.Future<List<_i3.JournalEntry>> getTodayEntries(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodayEntries,
          [userUuid],
        ),
        returnValue:
            _i5.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i5.Future<List<_i3.JournalEntry>>);

  @override
  _i5.Future<List<_i3.JournalEntry>> getEntriesByDateRange(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByDateRange,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue:
            _i5.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i5.Future<List<_i3.JournalEntry>>);

  @override
  _i5.Future<List<_i3.JournalEntry>> getEntriesByEmotion(
    String? userUuid,
    _i3.EmotionType? emotion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByEmotion,
          [
            userUuid,
            emotion,
          ],
        ),
        returnValue:
            _i5.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i5.Future<List<_i3.JournalEntry>>);

  @override
  _i5.Future<_i3.JournalEntry> updateEntry(_i3.JournalEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [entry],
        ),
        returnValue: _i5.Future<_i3.JournalEntry>.value(_FakeJournalEntry_2(
          this,
          Invocation.method(
            #updateEntry,
            [entry],
          ),
        )),
      ) as _i5.Future<_i3.JournalEntry>);

  @override
  _i5.Future<bool> deleteEntry(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [uuid],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  String? decryptContent(_i3.JournalEntry? entry) =>
      (super.noSuchMethod(Invocation.method(
        #decryptContent,
        [entry],
      )) as String?);

  @override
  String? decryptAiResponse(_i3.JournalEntry? entry) =>
      (super.noSuchMethod(Invocation.method(
        #decryptAiResponse,
        [entry],
      )) as String?);

  @override
  _i5.Future<Map<_i3.EmotionType, int>> getEmotionStatistics(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEmotionStatistics,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i5.Future<Map<_i3.EmotionType, int>>.value(
            <_i3.EmotionType, int>{}),
      ) as _i5.Future<Map<_i3.EmotionType, int>>);

  @override
  _i5.Future<List<_i3.JournalEntry>> getUnsyncedEntries(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedEntries,
          [userUuid],
        ),
        returnValue:
            _i5.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i5.Future<List<_i3.JournalEntry>>);

  @override
  _i5.Future<void> markAsSynced(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [uuid],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
