// Mocks generated by Mockito 5.4.4 from annotations
// in kokosid/test/core/services/productive_hour_predictor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kokosid/core/models/task.dart' as _i2;
import 'package:kokosid/core/repositories/task_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTask_0 extends _i1.SmartFake implements _i2.Task {
  _FakeTask_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i3.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Task> createTask(_i2.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
        ),
        returnValue: _i4.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #createTask,
            [task],
          ),
        )),
      ) as _i4.Future<_i2.Task>);

  @override
  _i4.Future<_i2.Task?> getTaskByUuid(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #getTaskByUuid,
          [uuid],
        ),
        returnValue: _i4.Future<_i2.Task?>.value(),
      ) as _i4.Future<_i2.Task?>);

  @override
  _i4.Future<List<_i2.Task>> getTasksByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByUser,
          [userUuid],
        ),
        returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<List<_i2.Task>> getPendingTasksByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingTasksByUser,
          [userUuid],
        ),
        returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<List<_i2.Task>> getCompletedTasksByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedTasksByUser,
          [userUuid],
        ),
        returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<List<_i2.Task>> getTodayTasks(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodayTasks,
          [userUuid],
        ),
        returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<List<_i2.Task>> getMicroTasks(String? originalTaskUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMicroTasks,
          [originalTaskUuid],
        ),
        returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<_i2.Task> updateTask(_i2.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i4.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #updateTask,
            [task],
          ),
        )),
      ) as _i4.Future<_i2.Task>);

  @override
  _i4.Future<_i2.Task> completeTask(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #completeTask,
          [uuid],
        ),
        returnValue: _i4.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #completeTask,
            [uuid],
          ),
        )),
      ) as _i4.Future<_i2.Task>);

  @override
  _i4.Future<_i2.Task> startTask(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #startTask,
          [uuid],
        ),
        returnValue: _i4.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #startTask,
            [uuid],
          ),
        )),
      ) as _i4.Future<_i2.Task>);

  @override
  _i4.Future<bool> deleteTask(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [uuid],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> getCompletedTaskCount(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedTaskCount,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> getTotalTaskCount(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalTaskCount,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i2.Task>> getTasksByDateRange(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByDateRange,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i4.Future<List<_i2.Task>>);
}
