// Mocks generated by Mockito 5.4.4 from annotations
// in kokosid/test/core/services/self_esteem_calculator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:kokosid/core/models/journal_entry.dart' as _i3;
import 'package:kokosid/core/models/self_esteem_score.dart' as _i4;
import 'package:kokosid/core/models/task.dart' as _i2;
import 'package:kokosid/core/repositories/journal_repository.dart' as _i8;
import 'package:kokosid/core/repositories/self_esteem_repository.dart' as _i5;
import 'package:kokosid/core/repositories/task_repository.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTask_0 extends _i1.SmartFake implements _i2.Task {
  _FakeTask_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJournalEntry_1 extends _i1.SmartFake implements _i3.JournalEntry {
  _FakeJournalEntry_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelfEsteemScore_2 extends _i1.SmartFake
    implements _i4.SelfEsteemScore {
  _FakeSelfEsteemScore_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMonthlyScoreStats_3 extends _i1.SmartFake
    implements _i5.MonthlyScoreStats {
  _FakeMonthlyScoreStats_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i6.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Task> createTask(_i2.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
        ),
        returnValue: _i7.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #createTask,
            [task],
          ),
        )),
      ) as _i7.Future<_i2.Task>);

  @override
  _i7.Future<_i2.Task?> getTaskByUuid(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #getTaskByUuid,
          [uuid],
        ),
        returnValue: _i7.Future<_i2.Task?>.value(),
      ) as _i7.Future<_i2.Task?>);

  @override
  _i7.Future<List<_i2.Task>> getTasksByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByUser,
          [userUuid],
        ),
        returnValue: _i7.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i7.Future<List<_i2.Task>>);

  @override
  _i7.Future<List<_i2.Task>> getPendingTasksByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingTasksByUser,
          [userUuid],
        ),
        returnValue: _i7.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i7.Future<List<_i2.Task>>);

  @override
  _i7.Future<List<_i2.Task>> getCompletedTasksByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedTasksByUser,
          [userUuid],
        ),
        returnValue: _i7.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i7.Future<List<_i2.Task>>);

  @override
  _i7.Future<List<_i2.Task>> getTodayTasks(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodayTasks,
          [userUuid],
        ),
        returnValue: _i7.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i7.Future<List<_i2.Task>>);

  @override
  _i7.Future<List<_i2.Task>> getMicroTasks(String? originalTaskUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMicroTasks,
          [originalTaskUuid],
        ),
        returnValue: _i7.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i7.Future<List<_i2.Task>>);

  @override
  _i7.Future<_i2.Task> updateTask(_i2.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i7.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #updateTask,
            [task],
          ),
        )),
      ) as _i7.Future<_i2.Task>);

  @override
  _i7.Future<_i2.Task> completeTask(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #completeTask,
          [uuid],
        ),
        returnValue: _i7.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #completeTask,
            [uuid],
          ),
        )),
      ) as _i7.Future<_i2.Task>);

  @override
  _i7.Future<_i2.Task> startTask(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #startTask,
          [uuid],
        ),
        returnValue: _i7.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #startTask,
            [uuid],
          ),
        )),
      ) as _i7.Future<_i2.Task>);

  @override
  _i7.Future<bool> deleteTask(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [uuid],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<int> getCompletedTaskCount(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedTaskCount,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> getTotalTaskCount(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalTaskCount,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<List<_i2.Task>> getTasksByDateRange(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByDateRange,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i7.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i7.Future<List<_i2.Task>>);
}

/// A class which mocks [JournalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalRepository extends _i1.Mock implements _i8.JournalRepository {
  MockJournalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.JournalEntry> createEntry(_i3.JournalEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEntry,
          [entry],
        ),
        returnValue: _i7.Future<_i3.JournalEntry>.value(_FakeJournalEntry_1(
          this,
          Invocation.method(
            #createEntry,
            [entry],
          ),
        )),
      ) as _i7.Future<_i3.JournalEntry>);

  @override
  _i7.Future<_i3.JournalEntry> createEncryptedEntry({
    required String? uuid,
    required String? userUuid,
    required String? content,
    String? audioUrl,
    _i3.EmotionType? emotion,
    double? emotionConfidence,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEncryptedEntry,
          [],
          {
            #uuid: uuid,
            #userUuid: userUuid,
            #content: content,
            #audioUrl: audioUrl,
            #emotion: emotion,
            #emotionConfidence: emotionConfidence,
          },
        ),
        returnValue: _i7.Future<_i3.JournalEntry>.value(_FakeJournalEntry_1(
          this,
          Invocation.method(
            #createEncryptedEntry,
            [],
            {
              #uuid: uuid,
              #userUuid: userUuid,
              #content: content,
              #audioUrl: audioUrl,
              #emotion: emotion,
              #emotionConfidence: emotionConfidence,
            },
          ),
        )),
      ) as _i7.Future<_i3.JournalEntry>);

  @override
  _i7.Future<_i3.JournalEntry?> getEntryByUuid(String? uuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntryByUuid,
          [uuid],
        ),
        returnValue: _i7.Future<_i3.JournalEntry?>.value(),
      ) as _i7.Future<_i3.JournalEntry?>);

  @override
  _i7.Future<List<_i3.JournalEntry>> getEntriesByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByUser,
          [userUuid],
        ),
        returnValue:
            _i7.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i7.Future<List<_i3.JournalEntry>>);

  @override
  _i7.Future<List<_i3.JournalEntry>> getTodayEntries(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodayEntries,
          [userUuid],
        ),
        returnValue:
            _i7.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i7.Future<List<_i3.JournalEntry>>);

  @override
  _i7.Future<List<_i3.JournalEntry>> getEntriesByDateRange(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByDateRange,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue:
            _i7.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i7.Future<List<_i3.JournalEntry>>);

  @override
  _i7.Future<List<_i3.JournalEntry>> getEntriesByEmotion(
    String? userUuid,
    _i3.EmotionType? emotion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByEmotion,
          [
            userUuid,
            emotion,
          ],
        ),
        returnValue:
            _i7.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i7.Future<List<_i3.JournalEntry>>);

  @override
  _i7.Future<_i3.JournalEntry> updateEntry(_i3.JournalEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [entry],
        ),
        returnValue: _i7.Future<_i3.JournalEntry>.value(_FakeJournalEntry_1(
          this,
          Invocation.method(
            #updateEntry,
            [entry],
          ),
        )),
      ) as _i7.Future<_i3.JournalEntry>);

  @override
  _i7.Future<bool> deleteEntry(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [uuid],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  String? decryptContent(_i3.JournalEntry? entry) =>
      (super.noSuchMethod(Invocation.method(
        #decryptContent,
        [entry],
      )) as String?);

  @override
  String? decryptAiResponse(_i3.JournalEntry? entry) =>
      (super.noSuchMethod(Invocation.method(
        #decryptAiResponse,
        [entry],
      )) as String?);

  @override
  _i7.Future<Map<_i3.EmotionType, int>> getEmotionStatistics(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEmotionStatistics,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i7.Future<Map<_i3.EmotionType, int>>.value(
            <_i3.EmotionType, int>{}),
      ) as _i7.Future<Map<_i3.EmotionType, int>>);

  @override
  _i7.Future<List<_i3.JournalEntry>> getUnsyncedEntries(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedEntries,
          [userUuid],
        ),
        returnValue:
            _i7.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i7.Future<List<_i3.JournalEntry>>);

  @override
  _i7.Future<void> markAsSynced(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [uuid],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [SelfEsteemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSelfEsteemRepository extends _i1.Mock
    implements _i5.SelfEsteemRepository {
  MockSelfEsteemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i4.SelfEsteemScore> createScore(_i4.SelfEsteemScore? score) =>
      (super.noSuchMethod(
        Invocation.method(
          #createScore,
          [score],
        ),
        returnValue:
            _i7.Future<_i4.SelfEsteemScore>.value(_FakeSelfEsteemScore_2(
          this,
          Invocation.method(
            #createScore,
            [score],
          ),
        )),
      ) as _i7.Future<_i4.SelfEsteemScore>);

  @override
  _i7.Future<_i4.SelfEsteemScore?> getScoreByUuid(String? uuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoreByUuid,
          [uuid],
        ),
        returnValue: _i7.Future<_i4.SelfEsteemScore?>.value(),
      ) as _i7.Future<_i4.SelfEsteemScore?>);

  @override
  _i7.Future<List<_i4.SelfEsteemScore>> getScoresByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoresByUser,
          [userUuid],
        ),
        returnValue: _i7.Future<List<_i4.SelfEsteemScore>>.value(
            <_i4.SelfEsteemScore>[]),
      ) as _i7.Future<List<_i4.SelfEsteemScore>>);

  @override
  _i7.Future<_i4.SelfEsteemScore?> getLatestScore(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestScore,
          [userUuid],
        ),
        returnValue: _i7.Future<_i4.SelfEsteemScore?>.value(),
      ) as _i7.Future<_i4.SelfEsteemScore?>);

  @override
  _i7.Future<_i4.SelfEsteemScore?> getTodayScore(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodayScore,
          [userUuid],
        ),
        returnValue: _i7.Future<_i4.SelfEsteemScore?>.value(),
      ) as _i7.Future<_i4.SelfEsteemScore?>);

  @override
  _i7.Future<List<_i4.SelfEsteemScore>> getScoresByDateRange(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoresByDateRange,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i7.Future<List<_i4.SelfEsteemScore>>.value(
            <_i4.SelfEsteemScore>[]),
      ) as _i7.Future<List<_i4.SelfEsteemScore>>);

  @override
  _i7.Future<List<_i4.SelfEsteemScore>> getRecentScores(
    String? userUuid,
    int? days,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentScores,
          [
            userUuid,
            days,
          ],
        ),
        returnValue: _i7.Future<List<_i4.SelfEsteemScore>>.value(
            <_i4.SelfEsteemScore>[]),
      ) as _i7.Future<List<_i4.SelfEsteemScore>>);

  @override
  _i7.Future<_i4.SelfEsteemScore> updateScore(_i4.SelfEsteemScore? score) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateScore,
          [score],
        ),
        returnValue:
            _i7.Future<_i4.SelfEsteemScore>.value(_FakeSelfEsteemScore_2(
          this,
          Invocation.method(
            #updateScore,
            [score],
          ),
        )),
      ) as _i7.Future<_i4.SelfEsteemScore>);

  @override
  _i7.Future<bool> deleteScore(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #deleteScore,
          [uuid],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<double?> getAverageScore(
    String? userUuid,
    int? days,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAverageScore,
          [
            userUuid,
            days,
          ],
        ),
        returnValue: _i7.Future<double?>.value(),
      ) as _i7.Future<double?>);

  @override
  _i7.Future<_i5.ScoreTrend> getScoreTrend(
    String? userUuid,
    int? days,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoreTrend,
          [
            userUuid,
            days,
          ],
        ),
        returnValue: _i7.Future<_i5.ScoreTrend>.value(_i5.ScoreTrend.improving),
      ) as _i7.Future<_i5.ScoreTrend>);

  @override
  _i7.Future<_i5.MonthlyScoreStats> getMonthlyStats(
    String? userUuid,
    DateTime? month,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthlyStats,
          [
            userUuid,
            month,
          ],
        ),
        returnValue:
            _i7.Future<_i5.MonthlyScoreStats>.value(_FakeMonthlyScoreStats_3(
          this,
          Invocation.method(
            #getMonthlyStats,
            [
              userUuid,
              month,
            ],
          ),
        )),
      ) as _i7.Future<_i5.MonthlyScoreStats>);
}
