// Mocks generated by Mockito 5.4.4 from annotations
// in kokosid/test/integration/end_to_end_flows_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i19;
import 'package:kokosid/core/models/journal_entry.dart' as _i3;
import 'package:kokosid/core/models/notification_tone.dart' as _i18;
import 'package:kokosid/core/models/self_esteem_score.dart' as _i4;
import 'package:kokosid/core/models/task.dart' as _i2;
import 'package:kokosid/core/models/user_context.dart' as _i6;
import 'package:kokosid/core/repositories/journal_repository.dart' as _i9;
import 'package:kokosid/core/repositories/self_esteem_repository.dart' as _i5;
import 'package:kokosid/core/repositories/task_repository.dart' as _i15;
import 'package:kokosid/core/services/achievement_streak_system.dart' as _i11;
import 'package:kokosid/core/services/ai_service.dart' as _i12;
import 'package:kokosid/core/services/dialogue_history_service.dart' as _i7;
import 'package:kokosid/core/services/emotion_analyzer.dart' as _i10;
import 'package:kokosid/core/services/notification_service.dart' as _i17;
import 'package:kokosid/core/services/text_emotion_classifier.dart' as _i8;
import 'package:kokosid/core/services/user_context_service.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTask_0 extends _i1.SmartFake implements _i2.Task {
  _FakeTask_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJournalEntry_1 extends _i1.SmartFake implements _i3.JournalEntry {
  _FakeJournalEntry_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelfEsteemScore_2 extends _i1.SmartFake
    implements _i4.SelfEsteemScore {
  _FakeSelfEsteemScore_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMonthlyScoreStats_3 extends _i1.SmartFake
    implements _i5.MonthlyScoreStats {
  _FakeMonthlyScoreStats_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserContext_4 extends _i1.SmartFake implements _i6.UserContext {
  _FakeUserContext_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDialogueEntry_5 extends _i1.SmartFake implements _i7.DialogueEntry {
  _FakeDialogueEntry_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePersonalizationContext_6 extends _i1.SmartFake
    implements _i7.PersonalizationContext {
  _FakePersonalizationContext_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextEmotionClassifier_7 extends _i1.SmartFake
    implements _i8.TextEmotionClassifier {
  _FakeTextEmotionClassifier_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJournalRepository_8 extends _i1.SmartFake
    implements _i9.JournalRepository {
  _FakeJournalRepository_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEmotionResult_9 extends _i1.SmartFake implements _i10.EmotionResult {
  _FakeEmotionResult_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreakStats_10 extends _i1.SmartFake implements _i11.StreakStats {
  _FakeStreakStats_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIService extends _i1.Mock implements _i12.AIService {
  MockAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<String> complete(String? prompt) => (super.noSuchMethod(
        Invocation.method(
          #complete,
          [prompt],
        ),
        returnValue: _i13.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #complete,
            [prompt],
          ),
        )),
      ) as _i13.Future<String>);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i15.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Task> createTask(_i2.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
        ),
        returnValue: _i13.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #createTask,
            [task],
          ),
        )),
      ) as _i13.Future<_i2.Task>);

  @override
  _i13.Future<_i2.Task?> getTaskByUuid(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #getTaskByUuid,
          [uuid],
        ),
        returnValue: _i13.Future<_i2.Task?>.value(),
      ) as _i13.Future<_i2.Task?>);

  @override
  _i13.Future<List<_i2.Task>> getTasksByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByUser,
          [userUuid],
        ),
        returnValue: _i13.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i13.Future<List<_i2.Task>>);

  @override
  _i13.Future<List<_i2.Task>> getPendingTasksByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingTasksByUser,
          [userUuid],
        ),
        returnValue: _i13.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i13.Future<List<_i2.Task>>);

  @override
  _i13.Future<List<_i2.Task>> getCompletedTasksByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedTasksByUser,
          [userUuid],
        ),
        returnValue: _i13.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i13.Future<List<_i2.Task>>);

  @override
  _i13.Future<List<_i2.Task>> getTodayTasks(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodayTasks,
          [userUuid],
        ),
        returnValue: _i13.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i13.Future<List<_i2.Task>>);

  @override
  _i13.Future<List<_i2.Task>> getMicroTasks(String? originalTaskUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMicroTasks,
          [originalTaskUuid],
        ),
        returnValue: _i13.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i13.Future<List<_i2.Task>>);

  @override
  _i13.Future<_i2.Task> updateTask(_i2.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i13.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #updateTask,
            [task],
          ),
        )),
      ) as _i13.Future<_i2.Task>);

  @override
  _i13.Future<_i2.Task> completeTask(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #completeTask,
          [uuid],
        ),
        returnValue: _i13.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #completeTask,
            [uuid],
          ),
        )),
      ) as _i13.Future<_i2.Task>);

  @override
  _i13.Future<_i2.Task> startTask(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #startTask,
          [uuid],
        ),
        returnValue: _i13.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #startTask,
            [uuid],
          ),
        )),
      ) as _i13.Future<_i2.Task>);

  @override
  _i13.Future<bool> deleteTask(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [uuid],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<int> getCompletedTaskCount(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedTaskCount,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i13.Future<int>.value(0),
      ) as _i13.Future<int>);

  @override
  _i13.Future<int> getTotalTaskCount(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalTaskCount,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i13.Future<int>.value(0),
      ) as _i13.Future<int>);

  @override
  _i13.Future<List<_i2.Task>> getTasksByDateRange(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByDateRange,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i13.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i13.Future<List<_i2.Task>>);
}

/// A class which mocks [JournalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalRepository extends _i1.Mock implements _i9.JournalRepository {
  MockJournalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i3.JournalEntry> createEntry(_i3.JournalEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEntry,
          [entry],
        ),
        returnValue: _i13.Future<_i3.JournalEntry>.value(_FakeJournalEntry_1(
          this,
          Invocation.method(
            #createEntry,
            [entry],
          ),
        )),
      ) as _i13.Future<_i3.JournalEntry>);

  @override
  _i13.Future<_i3.JournalEntry> createEncryptedEntry({
    required String? uuid,
    required String? userUuid,
    required String? content,
    String? audioUrl,
    _i3.EmotionType? emotion,
    double? emotionConfidence,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEncryptedEntry,
          [],
          {
            #uuid: uuid,
            #userUuid: userUuid,
            #content: content,
            #audioUrl: audioUrl,
            #emotion: emotion,
            #emotionConfidence: emotionConfidence,
          },
        ),
        returnValue: _i13.Future<_i3.JournalEntry>.value(_FakeJournalEntry_1(
          this,
          Invocation.method(
            #createEncryptedEntry,
            [],
            {
              #uuid: uuid,
              #userUuid: userUuid,
              #content: content,
              #audioUrl: audioUrl,
              #emotion: emotion,
              #emotionConfidence: emotionConfidence,
            },
          ),
        )),
      ) as _i13.Future<_i3.JournalEntry>);

  @override
  _i13.Future<_i3.JournalEntry?> getEntryByUuid(String? uuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntryByUuid,
          [uuid],
        ),
        returnValue: _i13.Future<_i3.JournalEntry?>.value(),
      ) as _i13.Future<_i3.JournalEntry?>);

  @override
  _i13.Future<List<_i3.JournalEntry>> getEntriesByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByUser,
          [userUuid],
        ),
        returnValue:
            _i13.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i13.Future<List<_i3.JournalEntry>>);

  @override
  _i13.Future<List<_i3.JournalEntry>> getTodayEntries(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodayEntries,
          [userUuid],
        ),
        returnValue:
            _i13.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i13.Future<List<_i3.JournalEntry>>);

  @override
  _i13.Future<List<_i3.JournalEntry>> getEntriesByDateRange(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByDateRange,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue:
            _i13.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i13.Future<List<_i3.JournalEntry>>);

  @override
  _i13.Future<List<_i3.JournalEntry>> getEntriesByEmotion(
    String? userUuid,
    _i3.EmotionType? emotion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByEmotion,
          [
            userUuid,
            emotion,
          ],
        ),
        returnValue:
            _i13.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i13.Future<List<_i3.JournalEntry>>);

  @override
  _i13.Future<_i3.JournalEntry> updateEntry(_i3.JournalEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [entry],
        ),
        returnValue: _i13.Future<_i3.JournalEntry>.value(_FakeJournalEntry_1(
          this,
          Invocation.method(
            #updateEntry,
            [entry],
          ),
        )),
      ) as _i13.Future<_i3.JournalEntry>);

  @override
  _i13.Future<bool> deleteEntry(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [uuid],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  String? decryptContent(_i3.JournalEntry? entry) =>
      (super.noSuchMethod(Invocation.method(
        #decryptContent,
        [entry],
      )) as String?);

  @override
  String? decryptAiResponse(_i3.JournalEntry? entry) =>
      (super.noSuchMethod(Invocation.method(
        #decryptAiResponse,
        [entry],
      )) as String?);

  @override
  _i13.Future<Map<_i3.EmotionType, int>> getEmotionStatistics(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEmotionStatistics,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i13.Future<Map<_i3.EmotionType, int>>.value(
            <_i3.EmotionType, int>{}),
      ) as _i13.Future<Map<_i3.EmotionType, int>>);

  @override
  _i13.Future<List<_i3.JournalEntry>> getUnsyncedEntries(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedEntries,
          [userUuid],
        ),
        returnValue:
            _i13.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i13.Future<List<_i3.JournalEntry>>);

  @override
  _i13.Future<void> markAsSynced(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [uuid],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [SelfEsteemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSelfEsteemRepository extends _i1.Mock
    implements _i5.SelfEsteemRepository {
  MockSelfEsteemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i4.SelfEsteemScore> createScore(_i4.SelfEsteemScore? score) =>
      (super.noSuchMethod(
        Invocation.method(
          #createScore,
          [score],
        ),
        returnValue:
            _i13.Future<_i4.SelfEsteemScore>.value(_FakeSelfEsteemScore_2(
          this,
          Invocation.method(
            #createScore,
            [score],
          ),
        )),
      ) as _i13.Future<_i4.SelfEsteemScore>);

  @override
  _i13.Future<_i4.SelfEsteemScore?> getScoreByUuid(String? uuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoreByUuid,
          [uuid],
        ),
        returnValue: _i13.Future<_i4.SelfEsteemScore?>.value(),
      ) as _i13.Future<_i4.SelfEsteemScore?>);

  @override
  _i13.Future<List<_i4.SelfEsteemScore>> getScoresByUser(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoresByUser,
          [userUuid],
        ),
        returnValue: _i13.Future<List<_i4.SelfEsteemScore>>.value(
            <_i4.SelfEsteemScore>[]),
      ) as _i13.Future<List<_i4.SelfEsteemScore>>);

  @override
  _i13.Future<_i4.SelfEsteemScore?> getLatestScore(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestScore,
          [userUuid],
        ),
        returnValue: _i13.Future<_i4.SelfEsteemScore?>.value(),
      ) as _i13.Future<_i4.SelfEsteemScore?>);

  @override
  _i13.Future<_i4.SelfEsteemScore?> getTodayScore(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodayScore,
          [userUuid],
        ),
        returnValue: _i13.Future<_i4.SelfEsteemScore?>.value(),
      ) as _i13.Future<_i4.SelfEsteemScore?>);

  @override
  _i13.Future<List<_i4.SelfEsteemScore>> getScoresByDateRange(
    String? userUuid,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoresByDateRange,
          [
            userUuid,
            start,
            end,
          ],
        ),
        returnValue: _i13.Future<List<_i4.SelfEsteemScore>>.value(
            <_i4.SelfEsteemScore>[]),
      ) as _i13.Future<List<_i4.SelfEsteemScore>>);

  @override
  _i13.Future<List<_i4.SelfEsteemScore>> getRecentScores(
    String? userUuid,
    int? days,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentScores,
          [
            userUuid,
            days,
          ],
        ),
        returnValue: _i13.Future<List<_i4.SelfEsteemScore>>.value(
            <_i4.SelfEsteemScore>[]),
      ) as _i13.Future<List<_i4.SelfEsteemScore>>);

  @override
  _i13.Future<_i4.SelfEsteemScore> updateScore(_i4.SelfEsteemScore? score) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateScore,
          [score],
        ),
        returnValue:
            _i13.Future<_i4.SelfEsteemScore>.value(_FakeSelfEsteemScore_2(
          this,
          Invocation.method(
            #updateScore,
            [score],
          ),
        )),
      ) as _i13.Future<_i4.SelfEsteemScore>);

  @override
  _i13.Future<bool> deleteScore(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #deleteScore,
          [uuid],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<double?> getAverageScore(
    String? userUuid,
    int? days,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAverageScore,
          [
            userUuid,
            days,
          ],
        ),
        returnValue: _i13.Future<double?>.value(),
      ) as _i13.Future<double?>);

  @override
  _i13.Future<_i5.ScoreTrend> getScoreTrend(
    String? userUuid,
    int? days,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoreTrend,
          [
            userUuid,
            days,
          ],
        ),
        returnValue:
            _i13.Future<_i5.ScoreTrend>.value(_i5.ScoreTrend.improving),
      ) as _i13.Future<_i5.ScoreTrend>);

  @override
  _i13.Future<_i5.MonthlyScoreStats> getMonthlyStats(
    String? userUuid,
    DateTime? month,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthlyStats,
          [
            userUuid,
            month,
          ],
        ),
        returnValue:
            _i13.Future<_i5.MonthlyScoreStats>.value(_FakeMonthlyScoreStats_3(
          this,
          Invocation.method(
            #getMonthlyStats,
            [
              userUuid,
              month,
            ],
          ),
        )),
      ) as _i13.Future<_i5.MonthlyScoreStats>);
}

/// A class which mocks [UserContextService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserContextService extends _i1.Mock
    implements _i16.UserContextService {
  MockUserContextService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i6.UserContext> getUserContext(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserContext,
          [userUuid],
        ),
        returnValue: _i13.Future<_i6.UserContext>.value(_FakeUserContext_4(
          this,
          Invocation.method(
            #getUserContext,
            [userUuid],
          ),
        )),
      ) as _i13.Future<_i6.UserContext>);
}

/// A class which mocks [DialogueHistoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogueHistoryService extends _i1.Mock
    implements _i7.DialogueHistoryService {
  MockDialogueHistoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i7.DialogueEntry> saveDialogue({
    required String? uuid,
    required String? userUuid,
    required String? userInput,
    required String? aiResponse,
    required String? actProcess,
    String? emotionType,
    double? emotionConfidence,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDialogue,
          [],
          {
            #uuid: uuid,
            #userUuid: userUuid,
            #userInput: userInput,
            #aiResponse: aiResponse,
            #actProcess: actProcess,
            #emotionType: emotionType,
            #emotionConfidence: emotionConfidence,
          },
        ),
        returnValue: _i13.Future<_i7.DialogueEntry>.value(_FakeDialogueEntry_5(
          this,
          Invocation.method(
            #saveDialogue,
            [],
            {
              #uuid: uuid,
              #userUuid: userUuid,
              #userInput: userInput,
              #aiResponse: aiResponse,
              #actProcess: actProcess,
              #emotionType: emotionType,
              #emotionConfidence: emotionConfidence,
            },
          ),
        )),
      ) as _i13.Future<_i7.DialogueEntry>);

  @override
  _i13.Future<List<_i7.DialogueEntry>> getDialogueHistory(
    String? userUuid, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDialogueHistory,
          [userUuid],
          {#limit: limit},
        ),
        returnValue:
            _i13.Future<List<_i7.DialogueEntry>>.value(<_i7.DialogueEntry>[]),
      ) as _i13.Future<List<_i7.DialogueEntry>>);

  @override
  _i13.Future<List<_i7.DialogueEntry>> getRecentDialogues(
    String? userUuid, {
    int? days = 7,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentDialogues,
          [userUuid],
          {
            #days: days,
            #limit: limit,
          },
        ),
        returnValue:
            _i13.Future<List<_i7.DialogueEntry>>.value(<_i7.DialogueEntry>[]),
      ) as _i13.Future<List<_i7.DialogueEntry>>);

  @override
  _i13.Future<List<_i7.DialogueEntry>> getDialoguesByEmotion(
    String? userUuid,
    String? emotionType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDialoguesByEmotion,
          [
            userUuid,
            emotionType,
          ],
        ),
        returnValue:
            _i13.Future<List<_i7.DialogueEntry>>.value(<_i7.DialogueEntry>[]),
      ) as _i13.Future<List<_i7.DialogueEntry>>);

  @override
  _i13.Future<_i7.PersonalizationContext> buildPersonalizationContext(
          String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildPersonalizationContext,
          [userUuid],
        ),
        returnValue: _i13.Future<_i7.PersonalizationContext>.value(
            _FakePersonalizationContext_6(
          this,
          Invocation.method(
            #buildPersonalizationContext,
            [userUuid],
          ),
        )),
      ) as _i13.Future<_i7.PersonalizationContext>);
}

/// A class which mocks [EmotionAnalyzer].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmotionAnalyzer extends _i1.Mock implements _i10.EmotionAnalyzer {
  MockEmotionAnalyzer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.TextEmotionClassifier get textClassifier => (super.noSuchMethod(
        Invocation.getter(#textClassifier),
        returnValue: _FakeTextEmotionClassifier_7(
          this,
          Invocation.getter(#textClassifier),
        ),
      ) as _i8.TextEmotionClassifier);

  @override
  _i9.JournalRepository get journalRepository => (super.noSuchMethod(
        Invocation.getter(#journalRepository),
        returnValue: _FakeJournalRepository_8(
          this,
          Invocation.getter(#journalRepository),
        ),
      ) as _i9.JournalRepository);

  @override
  _i13.Future<_i10.EmotionResult> analyzeText(
    String? text,
    String? userUuid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeText,
          [
            text,
            userUuid,
          ],
        ),
        returnValue: _i13.Future<_i10.EmotionResult>.value(_FakeEmotionResult_9(
          this,
          Invocation.method(
            #analyzeText,
            [
              text,
              userUuid,
            ],
          ),
        )),
      ) as _i13.Future<_i10.EmotionResult>);
}

/// A class which mocks [AchievementStreakSystem].
///
/// See the documentation for Mockito's code generation for more information.
class MockAchievementStreakSystem extends _i1.Mock
    implements _i11.AchievementStreakSystem {
  MockAchievementStreakSystem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> checkAndCelebrateStreak(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkAndCelebrateStreak,
          [userUuid],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<int> getCurrentStreak(String? userUuid) => (super.noSuchMethod(
        Invocation.method(
          #getCurrentStreak,
          [userUuid],
        ),
        returnValue: _i13.Future<int>.value(0),
      ) as _i13.Future<int>);

  @override
  _i13.Future<List<_i11.StreakRecord>> getTodayStreakRecords(
          String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodayStreakRecords,
          [userUuid],
        ),
        returnValue:
            _i13.Future<List<_i11.StreakRecord>>.value(<_i11.StreakRecord>[]),
      ) as _i13.Future<List<_i11.StreakRecord>>);

  @override
  _i13.Future<_i11.StreakStats> getWeeklyStreakStats(String? userUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeeklyStreakStats,
          [userUuid],
        ),
        returnValue: _i13.Future<_i11.StreakStats>.value(_FakeStreakStats_10(
          this,
          Invocation.method(
            #getWeeklyStreakStats,
            [userUuid],
          ),
        )),
      ) as _i13.Future<_i11.StreakStats>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i17.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> schedule({
    required _i18.NotificationMessage? message,
    required DateTime? scheduledTime,
    required _i18.RetryStrategy? retryStrategy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #schedule,
          [],
          {
            #message: message,
            #scheduledTime: scheduledTime,
            #retryStrategy: retryStrategy,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> sendImmediate(_i18.NotificationMessage? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendImmediate,
          [message],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> cancel(String? taskUuid) => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [taskUuid],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<List<_i19.PendingNotificationRequest>>
      getPendingNotifications() => (super.noSuchMethod(
            Invocation.method(
              #getPendingNotifications,
              [],
            ),
            returnValue:
                _i13.Future<List<_i19.PendingNotificationRequest>>.value(
                    <_i19.PendingNotificationRequest>[]),
          ) as _i13.Future<List<_i19.PendingNotificationRequest>>);
}
